### PR TITLE
Respeaker multi pr1040

### PR DESCRIPTION
**Pull request by iory**
cherry-picked from https://github.com/jsk-ros-pkg/jsk_3rdparty/pull/350

### CODE REVIEW

**Comment by 708yamaguchi** [comment]
Sorry, but there are conflicts...

**Comment by 708yamaguchi** [comment]
Maybe knorth55/pr1040 is rebased and force-pushed.

**Comment by iory** [comment]
OK. I rebased and force pushed.

**Comment by 708yamaguchi** [comment]
I am very sorry, but I forgot to merge this...

**Comment by iory** [comment]
Thanks!

**Pull request merged**
